[2025-03-02T00:00:13.553+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T00:00:13.558+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_daily_load.cleanup_old_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T00:00:13.561+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_daily_load.cleanup_old_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T00:00:13.561+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-02T00:00:13.564+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): cleanup_old_data> on 2025-03-01 00:00:00+00:00
[2025-03-02T00:00:13.569+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19261) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-02T00:00:13.569+0000] {standard_task_runner.py:72} INFO - Started process 19264 to run task
[2025-03-02T00:00:13.569+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_price_daily_load', 'cleanup_old_data', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/daily_stock_price.py', '--cfg-path', '/tmp/tmp_ao0cw8g']
[2025-03-02T00:00:13.570+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask cleanup_old_data
[2025-03-02T00:00:13.584+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_price_daily_load.cleanup_old_data scheduled__2025-03-01T00:00:00+00:00 [running]> on host 517e2fa4f5fd
[2025-03-02T00:00:13.607+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_daily_load' AIRFLOW_CTX_TASK_ID='cleanup_old_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T00:00:00+00:00'
[2025-03-02T00:00:13.607+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T00:00:13.612+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-03-02T00:00:13.612+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-02T00:00:13.612+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-02T00:00:14.128+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-02T00:00:14.918+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-02T00:00:14.919+0000] {logging_mixin.py:190} INFO - âœ… Cleaned up rows so that only the last 180 trading days remain for each symbol.
[2025-03-02T00:00:14.920+0000] {connection.py:788} INFO - closed
[2025-03-02T00:00:14.990+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-03-02T00:00:15.083+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T00:00:15.097+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T00:00:15.098+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_price_daily_load, task_id=cleanup_old_data, run_id=scheduled__2025-03-01T00:00:00+00:00, execution_date=20250301T000000, start_date=20250302T000013, end_date=20250302T000015
[2025-03-02T00:00:15.125+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T00:00:15.136+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T00:00:15.137+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
